FROM python:3.6.9-stretch

EXPOSE 7001

ENV ROOT /srv
ENV LT $ROOT/LanguageTool-4.9

RUN mkdir -p $ROOT
WORKDIR $ROOT

RUN apt-get update && apt-get install libhunspell-dev zip vim  -y
COPY entry-point-lt.sh /srv/entrypoint.sh

# LanguageTool
RUN apt-get install openjdk-8-jdk -y 
RUN wget -q https://languagetool.org/download/LanguageTool-4.9.zip && unzip LanguageTool-4.9.zip && rm -f LanguageTool-4.9.zip

ENTRYPOINT /srv/entrypoint.sh $LT
